const fs = require('fs');
const assert = require('assert');

const portal = fs.readFileSync('portal.jsx', 'utf8');
const app = fs.readFileSync('app.jsx', 'utf8');
const clients = fs.readFileSync('clients.jsx', 'utf8');
const rules = fs.readFileSync('firestore.rules.v2', 'utf8');
const index = fs.readFileSync('index.html', 'utf8');
let checks = 0;
const check = (value, message) => { assert.ok(value, message); checks += 1; };

check(index.includes('src="portal.jsx"'), 'el portal debe cargarse antes de montar la app');
check(app.includes('portalToken ? <ClientPortal'), 'el enlace debe abrir el portal sin entrar al gestor');
check(portal.includes('crypto.getRandomValues'), 'el token debe usar entropía criptográfica');
check(portal.includes("filter(project => String(project.client"), 'el portal debe limitarse al cliente correcto');
check(portal.includes('project.clientVisible !== false'), 'las tareas del cliente deben publicarse salvo exclusión explícita');
check(fs.readFileSync('data.jsx', 'utf8').includes('clientVisible: p.clientVisible !== false'), 'los documentos anteriores deben ser visibles por compatibilidad');
check(!portal.includes('comments:'), 'la proyección no debe exponer comentarios internos');
check(!portal.includes('budget:'), 'la proyección no debe exponer presupuesto');
check(!portal.includes('assignees:'), 'la proyección no debe exponer responsables');
check(clients.includes('Publicar portal'), 'el perfil debe permitir publicar el portal');
check(clients.includes("p.clientVisible !== false ? 'Visible' : 'Oculta'"), 'cada tarea debe mostrar su visibilidad');
check(rules.includes('match /frame_client_portals/{token}'), 'las reglas deben cubrir la colección nueva');
check(rules.includes('allow get: if resource.data.published == true'), 'sólo un portal publicado debe ser legible');
check(rules.includes('allow list: if false'), 'nadie debe enumerar portales');
check(rules.includes('data.tasks.size() <= 100'), 'la proyección debe tener un límite');
check(rules.includes("data.keys().hasOnly(['workspaceId', 'clientId', 'clientName', 'studioName', 'published', 'updatedAt', 'taskIds', 'tasks'])"), 'el documento público debe rechazar campos privados');
check(portal.includes('Calendario mensual del trabajo'), 'el portal debe mostrar un calendario accesible');
check(portal.includes('calendarDays.map'), 'el calendario debe renderizar su cuadrícula mensual');
check(portal.includes('moveMonth(-1)'), 'el cliente debe poder navegar al mes anterior');
check(portal.includes('moveMonth(1)'), 'el cliente debe poder navegar al mes siguiente');
check(portal.includes('tasksByDate[iso]'), 'las tareas deben ubicarse por fecha en el calendario');
check(fs.readFileSync('frame.css', 'utf8').includes('grid-template-columns: repeat(7, minmax(150px, 1fr))'), 'el calendario debe conservar siete días con columnas legibles');
check(portal.includes('max-w-[1440px]'), 'el portal debe aprovechar pantallas amplias');
check(portal.includes('image: /^https:'), 'la proyección debe aceptar únicamente imágenes https');
check(portal.includes('url: /^https:'), 'la proyección debe aceptar únicamente enlaces https');
check(portal.includes('portal-calendar-thumb'), 'la imagen debe aparecer como miniatura en el calendario');
check(portal.includes('setOpenTask(task)'), 'la tarjeta del calendario debe abrir su detalle');
check(portal.includes('Abrir enlace compartido'), 'el detalle debe mostrar la URL pública');
check(portal.includes('<SharedClientComments'), 'el detalle público debe incluir conversación');
check(fs.readFileSync('modal.jsx', 'utf8').includes('Información para el cliente'), 'la tarjeta creativa debe editar campos públicos');
check(fs.readFileSync('modal.jsx', 'utf8').includes('Conversación con el cliente'), 'la conversación debe aparecer en la tarjeta creativa');
check(fs.readFileSync('modal.jsx', 'utf8').includes("collection('comments')"), 'los comentarios deben sincronizarse en tiempo real');
check(rules.includes('match /comments/{commentId}'), 'las reglas deben cubrir comentarios del portal');
check(rules.includes("request.resource.data.authorType == 'client'"), 'el visitante sólo debe escribir como cliente');
check(rules.includes('request.resource.data.text.size() <= 2000'), 'los comentarios deben tener límite de tamaño');
check(rules.includes('allow update: if false'), 'los comentarios compartidos deben ser inmutables');
check(rules.includes('request.resource.data.projectId in portal().taskIds'), 'sólo se debe comentar una tarea publicada');
check(portal.includes('const calendarScrollRef = React.useRef(null)'), 'el calendario debe controlar su contenedor desplazable');
check(portal.includes("addEventListener('wheel', onWheel, { passive: false })"), 'el trackpad debe activar desplazamiento horizontal');
check(portal.includes('calendar.scrollLeft += rawDelta * scale'), 'el gesto debe mover el calendario');
check(portal.includes('horizontalGesture ? event.deltaX : event.deltaY'), 'debe aceptar trackpad y Shift+rueda');
check(portal.includes("removeEventListener('wheel', onWheel)"), 'el listener debe limpiarse al desmontar');
check(fs.readFileSync('frame.css', 'utf8').includes('touch-action: pan-x pan-y'), 'el gesto táctil debe permanecer habilitado');
check(portal.includes('h-screen overflow-y-auto'), 'el portal debe crear su propio viewport vertical desplazable');
check(portal.includes('portal-page-scroll'), 'el scroll vertical debe tener una regla específica');
check(fs.readFileSync('frame.css', 'utf8').includes('overscroll-behavior-y: contain'), 'el scroll vertical debe permanecer contenido en el portal');

console.log(`client-portal-contract: ${checks} checks passed`);
