const fs = require('fs');
const assert = require('assert');

const portal = fs.readFileSync('portal.jsx', 'utf8');
const app = fs.readFileSync('app.jsx', 'utf8');
const clients = fs.readFileSync('clients.jsx', 'utf8');
const rules = fs.readFileSync('firestore.rules.v2', 'utf8');
const index = fs.readFileSync('index.html', 'utf8');
let checks = 0;
const check = (value, message) => { assert.ok(value, message); checks += 1; };

check(index.includes('src="portal.jsx"'), 'el portal debe cargarse antes de montar la app');
check(app.includes('portalToken ? <ClientPortal'), 'el enlace debe abrir el portal sin entrar al gestor');
check(portal.includes('crypto.getRandomValues'), 'el token debe usar entropía criptográfica');
check(portal.includes("filter(project => String(project.client"), 'el portal debe limitarse al cliente correcto');
check(portal.includes('project.clientVisible !== false'), 'las tareas del cliente deben publicarse salvo exclusión explícita');
check(fs.readFileSync('data.jsx', 'utf8').includes('clientVisible: p.clientVisible !== false'), 'los documentos anteriores deben ser visibles por compatibilidad');
check(!portal.includes('comments:'), 'la proyección no debe exponer comentarios internos');
check(!portal.includes('budget:'), 'la proyección no debe exponer presupuesto');
check(!portal.includes('assignees:'), 'la proyección no debe exponer responsables');
check(clients.includes('Publicar portal'), 'el perfil debe permitir publicar el portal');
check(clients.includes("p.clientVisible !== false ? 'Visible' : 'Oculta'"), 'cada tarea debe mostrar su visibilidad');
check(rules.includes('match /frame_client_portals/{token}'), 'las reglas deben cubrir la colección nueva');
check(rules.includes('allow get: if resource.data.published == true'), 'sólo un portal publicado debe ser legible');
check(rules.includes('allow list: if false'), 'nadie debe enumerar portales');
check(rules.includes('data.tasks.size() <= 100'), 'la proyección debe tener un límite');
check(rules.includes("data.keys().hasOnly(['workspaceId', 'clientId', 'clientName', 'clientInitials', 'clientColor', 'studioName', 'studioAvatar', 'published', 'updatedAt', 'taskIds', 'tasks'])"), 'el documento público debe rechazar campos privados');
check(portal.includes('Calendario mensual del trabajo'), 'el portal debe mostrar un calendario accesible');
check(portal.includes('calendarDays.map'), 'el calendario debe renderizar su cuadrícula mensual');
check(portal.includes('moveMonth(-1)'), 'el cliente debe poder navegar al mes anterior');
check(portal.includes('moveMonth(1)'), 'el cliente debe poder navegar al mes siguiente');
check(portal.includes('tasksByDate[iso]'), 'las tareas deben ubicarse por fecha en el calendario');
check(fs.readFileSync('frame.css', 'utf8').includes('grid-template-columns: repeat(7, minmax(150px, 1fr))'), 'el calendario debe conservar siete días con columnas legibles');
check(portal.includes('max-w-[1440px]'), 'el portal debe aprovechar pantallas amplias');
check(portal.includes("task.deliverables?.find(item => item.kind === 'photos'"), 'una imagen entregable debe aparecer como miniatura en el calendario');
check(portal.includes('setOpenTask(task)'), 'la tarjeta del calendario debe abrir su detalle');
check(portal.includes('Recursos compartidos'), 'el detalle debe reutilizar los entregables normales');
check(portal.includes('<SharedClientComments'), 'el detalle público debe incluir conversación');
check(!fs.readFileSync('modal.jsx', 'utf8').includes('Información para el cliente'), 'la tarjeta creativa no debe tener un bloque público pegado');
check(fs.readFileSync('modal.jsx', 'utf8').includes("label:'Chat'"), 'el chat compartido debe aparecer con un nombre simple');
check(!fs.readFileSync('modal.jsx', 'utf8').includes('El cliente y el equipo ven esta misma conversación.'), 'el chat no debe mostrar explicaciones redundantes');
check(fs.readFileSync('data.jsx', 'utf8').includes("avatar:   m?.avatar"), 'la ficha del tablero debe conservar el avatar del perfil');
check(portal.includes('studioAvatar:'), 'el portal debe proyectar sólo el avatar público del estudio');
check(rules.includes("data.studioAvatar.matches('data:image/(jpeg|png|webp);base64,.*')"), 'las reglas deben limitar el formato del avatar público');
check(fs.readFileSync('modal.jsx', 'utf8').includes('Usar esta imagen como portada'), 'una imagen entregable debe poder usarse como portada');
check(fs.readFileSync('modal.jsx', 'utf8').includes('aria-expanded={activityOpen}'), 'la actividad debe ser desplegable y accesible');
check(fs.readFileSync('modal.jsx', 'utf8').includes('<Icon name="image" size={13} /> Imagen'), 'los recursos deben ofrecer una acción compacta para imágenes');
check(fs.readFileSync('modal.jsx', 'utf8').includes('<Icon name="paperclip" size={13} /> Archivo'), 'los recursos deben ofrecer una acción compacta para documentos');
check(fs.readFileSync('modal.jsx', 'utf8').includes('setLinkOpen(open => !open)'), 'el formulario de enlace debe abrirse sólo cuando se solicita');
check(fs.readFileSync('modal.jsx', 'utf8').includes('onPaste={onPaste}'), 'el chat debe aceptar imágenes pegadas');
check(fs.readFileSync('modal.jsx', 'utf8').includes('Agregar emoji'), 'el chat debe ofrecer emojis');
check(!fs.readFileSync('modal.jsx', 'utf8').includes('Agregar entregable'), 'los recursos no deben esconderse dentro de un formulario de entregable');
check(fs.readFileSync('modal.jsx', 'utf8').includes('Enlace externo'), 'el enlace debe ser un campo independiente');
check(!fs.readFileSync('modal.jsx', 'utf8').includes("dv.url.replace(/^https?:\\/\\//"), 'la interfaz no debe mostrar la URL técnica del recurso');
check(fs.readFileSync('modal.jsx', 'utf8').includes("dv.status === 'ready' ? 'Compartido' : 'Privado'"), 'la visibilidad del recurso debe expresarse con lenguaje comprensible');
check(!portal.includes('openTask.checklist'), 'el cliente no debe ver el checklist interno');
check(fs.readFileSync('modal.jsx', 'utf8').includes("collection('comments')"), 'los comentarios deben sincronizarse en tiempo real');
check(rules.includes('match /comments/{commentId}'), 'las reglas deben cubrir comentarios del portal');
check(rules.includes("request.resource.data.authorType == 'client'"), 'el visitante sólo debe escribir como cliente');
check(rules.includes('request.resource.data.authorName == portal().clientName'), 'el visitante debe escribir con la identidad del perfil del cliente');
check(portal.includes('clientInitials={portal.clientInitials'), 'el chat público debe usar el avatar definido del cliente');
check(!fs.readFileSync('modal.jsx', 'utf8').includes('placeholder="Tu nombre"'), 'el portal no debe pedir un nombre dentro del chat');
check(fs.readFileSync('modal.jsx', 'utf8').includes('<Icon name="smile" size={17}'), 'la sonrisa sin círculo debe compensar ópticamente su menor superficie');
check(fs.readFileSync('icons.jsx', 'utf8').includes('<circle cx="8" cy="9" r="1" fill="currentColor" stroke="none"/>'), 'la sonrisa debe tener ojos legibles sin recuperar el contorno circular');
check(!fs.readFileSync('icons.jsx', 'utf8').includes('smile: <><circle cx="12" cy="12"'), 'la sonrisa no debe volver a encerrarse en un círculo');
check(fs.readFileSync('modal.jsx', 'utf8').includes('<Icon name="send" size={16}'), 'el envío debe usar un icono minimalista proporcionado');
check(fs.readFileSync('modal.jsx', 'utf8').includes('aria-label="Adjuntar imagen"'), 'el clip debe tener un nombre accesible');
check(fs.readFileSync('modal.jsx', 'utf8').includes('aria-pressed={emojiOpen}'), 'el selector de emojis debe exponer su estado');
check(fs.readFileSync('modal.jsx', 'utf8').includes("event.key === 'Enter' && !event.shiftKey"), 'Enter debe enviar y Shift+Enter debe conservar el salto de línea');
check(fs.readFileSync('modal.jsx', 'utf8').includes('Enter para enviar · Shift + Enter para una nueva línea'), 'el chat debe explicar el atajo sin recargar el compositor');
check(fs.readFileSync('modal.jsx', 'utf8').includes('aria-live="polite"'), 'la conversación debe anunciar mensajes nuevos sin interrumpir');
check(fs.readFileSync('modal.jsx', 'utf8').includes('Iniciá la conversación'), 'el estado vacío debe invitar a conversar con lenguaje breve');
check(fs.readFileSync('modal.jsx', 'utf8').includes("listRef.current.scrollTop = listRef.current.scrollHeight"), 'el chat debe mantener visible el mensaje más reciente');
check(!fs.readFileSync('modal.jsx', 'utf8').includes('<FormatBtn'), 'el chat interno no debe mostrar controles decorativos sin función');
check(rules.includes('request.resource.data.text.size() <= 2000'), 'los comentarios deben tener límite de tamaño');
check(rules.includes("'attachmentUrl', 'attachmentName'"), 'los comentarios deben admitir una imagen compartida');
check(rules.includes("attachmentUrl.matches('https://firebasestorage.googleapis.com/.*')"), 'la imagen del chat debe venir del almacenamiento controlado');
check(rules.includes("affectedKeys().hasOnly(['text', 'editedAt'])"), 'la edición sólo debe cambiar el texto y su marca temporal');
check(rules.includes('allow delete: if isMember(portal().workspaceId)'), 'sólo el equipo debe poder eliminar comentarios');
check(fs.readFileSync('modal.jsx', 'utf8').includes('Editar comentario'), 'el equipo debe poder editar sus comentarios');
check(fs.readFileSync('modal.jsx', 'utf8').includes('Eliminar comentario'), 'el equipo debe poder moderar y eliminar comentarios');
check(rules.includes('request.resource.data.projectId in portal().taskIds'), 'sólo se debe comentar una tarea publicada');
check(portal.includes('const calendarScrollRef = React.useRef(null)'), 'el calendario debe controlar su contenedor desplazable');
check(portal.includes("addEventListener('wheel', onWheel, { passive: false })"), 'el trackpad debe activar desplazamiento horizontal');
check(portal.includes('calendar.scrollLeft += rawDelta * scale'), 'el gesto debe mover el calendario');
check(portal.includes('horizontalGesture ? event.deltaX : event.deltaY'), 'debe aceptar trackpad y Shift+rueda');
check(portal.includes("removeEventListener('wheel', onWheel)"), 'el listener debe limpiarse al desmontar');
check(fs.readFileSync('frame.css', 'utf8').includes('touch-action: pan-x pan-y'), 'el gesto táctil debe permanecer habilitado');
check(portal.includes('h-screen overflow-y-auto'), 'el portal debe crear su propio viewport vertical desplazable');
check(portal.includes('portal-page-scroll'), 'el scroll vertical debe tener una regla específica');
check(fs.readFileSync('frame.css', 'utf8').includes('overscroll-behavior-y: contain'), 'el scroll vertical debe permanecer contenido en el portal');

console.log(`client-portal-contract: ${checks} checks passed`);
