const {createServer}=require('./portfolio-preview-server.cjs');
const path=require('node:path'),assert=require('node:assert/strict');
const deps=process.env.FRAME_TEST_DEPS||'C:/Users/ANGEL M/Documents/TOONED-OS/node_modules';
const {chromium}=require(path.join(deps,'playwright'));
(async()=>{
  const server=createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
  try {
    browser=await chromium.launch({channel:'chrome',headless:true});
    const page=await browser.newPage({viewport:{width:1440,height:940},reducedMotion:'no-preference'});
    page.setDefaultTimeout(8000);
    const errors=[];page.on('pageerror',e=>errors.push(e.message));
    const origin='http://127.0.0.1:'+server.address().port;
    await page.route('**/*',r=>r.request().url().startsWith(origin)?r.continue():r.abort());
    await page.goto(origin+'/?demo=1');
    await page.getByRole('button',{name:'Diseño',exact:true}).click();
    assert.equal(await page.getByLabel('Efecto de animación').inputValue(),'none');
    await page.getByLabel('Efecto de animación').selectOption('rise');
    await page.getByRole('button',{name:'Pausada',exact:true}).click();
    const hero=page.locator('.fp-site-hero');
    assert.equal(await hero.evaluate(e=>e.getAnimations().length),0,'Editing stays still until replay');
    const height=await hero.evaluate(e=>e.offsetHeight);
    await page.getByRole('button',{name:'Probar animación',exact:true}).click();
    await page.waitForFunction(()=>document.querySelector('.fp-site-hero').getAnimations().length===1);
    assert.equal(await hero.evaluate(e=>e.getAnimations()[0].effect.getTiming().duration),800);
    assert.equal(await hero.evaluate(e=>e.offsetHeight),height,'Motion does not change layout');
    await page.emulateMedia({reducedMotion:'reduce'});
    await page.waitForFunction(()=>document.querySelector('.fp-site-hero').getAnimations().length===0);
    assert.equal(await hero.evaluate(e=>getComputedStyle(e).opacity),'1');
    assert.ok(await page.getByRole('button',{name:'Probar animación',exact:true}).isDisabled());
    await page.emulateMedia({reducedMotion:'no-preference'});
    await page.locator('.fp-tree-select').nth(1).click();
    await page.getByRole('button',{name:'Diseño',exact:true}).click();
    await page.getByLabel('Efecto de animación').selectOption('stagger');
    await page.getByRole('button',{name:'Pausada',exact:true}).click();
    await page.getByRole('button',{name:'Probar animación',exact:true}).click();
    await page.waitForFunction(()=>document.querySelector('.fp-site-gallery').getAnimations({subtree:true}).length===3);
    assert.deepEqual(await page.locator('.fp-site-gallery').evaluate(e=>e.getAnimations({subtree:true}).map(a=>a.effect.getTiming().delay)),[0,70,140]);
    await page.locator('.fp-site-gallery').evaluate(e=>Promise.all(e.getAnimations({subtree:true}).map(a=>a.finished.catch(()=>{}))));
    assert.equal(await page.locator('.fp-site-gallery').evaluate(e=>e.getAnimations({subtree:true}).length),0);
    await page.getByRole('button',{name:'Guardar borrador',exact:true}).click();
    await page.reload();
    assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('frame_portfolio_v1_demo_local')).sections[1].design.animation),'stagger');
    await page.getByRole('button',{name:'Vista previa',exact:true}).click();
    await page.waitForFunction(()=>document.querySelector('.fp-site-hero').getAnimations().length===1);
    await page.emulateMedia({reducedMotion:'reduce'});
    await page.waitForFunction(()=>document.querySelectorAll('.fp-site-section').length>0&&Array.from(document.querySelectorAll('.fp-site-section')).every(e=>e.getAnimations({subtree:true}).length===0));
    await page.getByRole('button',{name:'Volver al editor',exact:true}).click();
    await page.locator('.fp-tree-select').nth(0).click();
    await page.getByRole('button',{name:'Diseño',exact:true}).click();
    await page.getByLabel('Efecto de animación').selectOption('none');
    await page.getByRole('button',{name:'Vista previa',exact:true}).click();
    assert.equal(await hero.evaluate(e=>e.getAnimations().length),0);
    assert.deepEqual(errors,[]);
    console.log('Portfolio motion: opt-in, manual replay, layout stability, stagger timing, save/reload, preview and live reduced-motion cancellation OK');
  } finally {if(browser)await browser.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1;});
