const assert = require('node:assert/strict');
const fs = require('node:fs');

const html = fs.readFileSync('index.html', 'utf8');
const css = fs.readFileSync('frame.css', 'utf8');
const app = fs.readFileSync('app.jsx', 'utf8');
const modal = fs.readFileSync('modal.jsx', 'utf8');
const mobile = fs.readFileSync('mobile.jsx', 'utf8');
const data = fs.readFileSync('data.jsx', 'utf8');
const routine = fs.readFileSync('routine.jsx', 'utf8');
const clients = fs.readFileSync('clients.jsx', 'utf8');

assert.match(html, /frame_theme/);
assert.match(html, /window\.setFrameTheme/);
assert.match(html, /document\.documentElement\.dataset\.theme/);
assert.match(html, /meta\[name="theme-color"\]/);
assert.match(html, /rel="icon" type="image\/svg\+xml" href="favicon\.svg"/);
assert.doesNotMatch(html, /d4ff4f/i);
assert.match(css, /html\[data-theme="light"\]/);
assert.match(css, /--color-scheme:\s*light/);
assert.match(css, /--bg:\s*#ececf1/);
assert.match(css, /--surface:\s*#ffffff/);
assert.match(css, /--surface-2:\s*#e2e2e7/);
assert.match(css, /--accent:\s*#18181b/);
assert.match(css, /--accent-on:\s*#ffffff/);
assert.match(css, /--resource-blue:\s*#104b82/);
assert.match(css, /--resource-violet:\s*#2a105c/);
assert.match(css, /--resource-green:\s*#087a3d/);
assert.match(css, /--resource-orange:\s*#7b5900/);
assert.match(css, /--resource-blue:\s*#39a8ff/);
assert.match(css, /--resource-violet:\s*#aa72ff/);
assert.match(css, /--accent-border:\s*rgba\(24, 24, 27, 0\.36\)/);
assert.match(css, /\.text-white\s*\{\s*color:\s*var\(--text\)/);
assert.match(app, /label="Modo claro"/);
assert.match(app, /window\.setFrameTheme\(next\)/);
assert.match(app, /isPinned \? 'var\(--accent-on\)'/);
assert.match(mobile, /window\.setFrameTheme\(next\)/);
assert.match(mobile, /Cambiar a modo oscuro/);
assert.match(mobile, /Cambiar a modo claro/);
assert.doesNotMatch(app + modal, /colorScheme:\s*'dark'/);
assert.match(data, /const LEGACY_THEME_COLORS/);
assert.match(data, /'#6cc4ff': 'var\(--resource-blue\)'/);
assert.match(data, /'#c089ff': 'var\(--resource-violet\)'/);
assert.match(data, /const resolveThemeColor/);
assert.match(routine, /background: allDone \? 'var\(--accent\)' : 'var\(--resource-green\)'/);
assert.doesNotMatch(routine, /rgba\(212,255,79/);
assert.doesNotMatch(routine, /#6CC4FF/);
assert.match(modal, /const coverTextColor/);
assert.match(modal, /contrastWithWhite >= contrastWithBlack/);
assert.match(modal, /linear-gradient\(to top, rgba\(0,0,0,.76\)/);
assert.match(modal, />Tableros<\/span>/);
assert.match(modal, /resolveThemeColor\(user\.color\)/);
assert.match(clients, /resolveThemeColor\(client\.color\)/);
assert.match(clients, /resolveThemeColor\(matched\.color\)/);
assert.match(modal, /const StatusPill = \(\{ status, size = 'sm', solid = false \}\)/);
assert.match(modal, /const TypePill = \(\{ type, size = 'sm', solid = false \}\)/);
assert.match(modal, /const PriorityBadge = \(\{ priority, solid = false \}\)/);
assert.match(modal, /<TypePill type=\{project\.type\} size="md" solid \/>/);
assert.match(modal, /<StatusPill status=\{project\.status\} size="md" solid \/>/);
assert.match(modal, /<PriorityBadge priority=\{project\.priority\} solid \/>/);

console.log('theme-contract: 48 checks passed');
